version: '3.1'
services:
    server:
        build: ./server
        restart: always
        volumes:
            - ./server/app:/code/app
        ports:
            - 8000:8000
        networks:
            - web_network

    grafana:
        image: grafana/grafana-enterprise
        ports:
            - 3000:3000

    # nginx:
    #     image: nginx:latest
    #     ports:
    #         - 8000:80
    #     volumes:
    #         - web-root:/var/www/html
    #         - ./config/nginx:/etc/nginx/conf.d/
    #     depends_on:
    #         - frontend
    #         - backend
    #         - db_interface
    #     networks:
    #         - web_network

networks:
    web_network:
        driver: bridge
