version: '3.1'
services:
    server:
        build: ./server
        restart: always
        volumes:
            - ./server/app:/code/app
        ports:
            - 8000:8000
        networks:
            - web_network
        environment:
            DATABASE_URL: $INFLUX_DB_URL
            DATABASE_TOKEN: $INFLUX_DB_TOKEN

    grafana:
        image: grafana/grafana-enterprise
        ports:
            - 3000:3000
        volumes:
            - grafana_vol:/var/lib/grafana
        environment:
                GF_AUTH_ANONYMOUS_ENABLED: 'true'
                GF_AUTH_ANONYMOUS_ORG_NAME: Main Org.
                GF_AUTH_ANONYMOUS_ORG_ROLE: Viewer
                GF_AUTH_ANONYMOUS_HIDE_VERSION: 'true'

networks:
    web_network:
        driver: bridge

volumes:
    grafana_vol:
